server:
  port: 9099

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: smart-guru
    password: i-know-pass

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml