CREATE TABLE IF NOT EXISTS certificates (
id UUID PRIMARY KEY,
course_id UUID NOT NULL,
organizer_id UUID NOT NULL,
user_id UUID NOT NULL,
course_name VARCHAR(255) NOT NULL,
course_number VARCHAR(255) NOT NULL,
certificate_photo VARCHAR(255),
issue_date DATETIME NOT NULL,
creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
delete_date DATETIME
    );