server:
  port: 9085

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      driverClassName: org.postgresql.Driver
      username: smart-guru
      password: i-know-pass

    jpa:
      database-platform: org.hibernate.dialect.PostgeSQLDialect
      hibernate:
        ddl-auto: validate