CREATE TABLE IF NOT EXISTS address
(
  address_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  city VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL,
  house VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS photos_course
(
  photos_course_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  photos VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews
(
  reviews_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS course
(
  course_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  number_seats FLOAT NOT NULL,
  price FLOAT NOT NULL,
  photo_profile VARCHAR(255) NOT NULL,
  reviews_id FLOAT NOT NULL,
  address_id FLOAT NOT NULL,
  photos_course_id FLOAT NOT NULL,

  CONSTRAINT fk_course_to_reviews FOREIGN KEY (reviews_id) REFERENCES reviews (reviews_id) ON DELETE CASCADE,
  CONSTRAINT fk_course_to_address FOREIGN KEY (address_id) REFERENCES address (address_id) ON DELETE CASCADE,
  CONSTRAINT fk_course_to_photos FOREIGN KEY (photos_course_id) REFERENCES photos_course (photos_course_id) ON DELETE CASCADE
);
